---

- name: "Setting kodi directory to /home/{{ kodi_os_user }}"
  ansible.builtin.set_fact:
    kodi_path: "/home/{{ kodi_os_user }}"
    kodi_systemd_location: /etc/systemd/system/
  when:
    - kodi_os_user | length > 0
    - ansible_distribution != "LibreELEC"

- name: Setting kodi variables for openelec
  ansible.builtin.set_fact:
    kodi_os_user: "root"
    kodi_path: "/storage"
    kodi_systemd_location: /storage/.config/system.d
  when: ansible_distribution == "LibreELEC"

- name: Install kodi on ubuntu
  when: ansible_distribution != "LibreELEC"
  block:
    # install package on ubuntu hosts as flatpak since the PPA is abandoned

    - name: Setting kodi user data directory for flatpak
      ansible.builtin.set_fact:
        kodi_data_dir: ".var/app/tv.kodi.Kodi/data/userdata"

    - name: Ensure no kodi package is installed from apt sources
      ansible.builtin.package:
        name: kodi
        state: absent
      become: true
      become_user: root

    - name: Remove legacy apt list file
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/ppa_team_xbmc_ppa_jammy.list
        state: absent
      become: true
      become_user: root

    - name: Remove legacy apt source file
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/kodi-ppa.source
        state: absent
      become: true
      become_user: root

    - name: Ensure flatpak is installed
      ansible.builtin.package:
        name: flatpak
        state: present
      become: true
      become_user: root

    - name: Enable the flathub remote in the system installation
      community.general.flatpak_remote:
        name: flathub
        state: present
        enabled: true
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
      become: true
      become_user: root

    - name: Install Kodi
      community.general.flatpak:
        name: tv.kodi.Kodi
        state: present
        remote: flathub
      become: true
      become_user: root

  rescue:
    - name: Show rescue debug message
      ansible.builtin.debug:
        msg: "Kodi not available on this Ubuntu release"

- name: Create config directory
  ansible.builtin.file:
    path: "{{ kodi_path }}/{{ kodi_data_dir }}/"
    state: directory
    mode: "0755"
    owner: "{{ kodi_os_user }}"
    group: "{{ kodi_os_user }}"
  become: true
  become_user: root

- name: Put kodi configuration in place
  ansible.builtin.template:
    src: advancedsettings.xml.jinja2
    dest: "{{ kodi_path }}/{{ kodi_data_dir }}/advancedsettings.xml"
    owner: "{{ kodi_os_user }}"
    group: "{{ kodi_os_user }}"
    mode: "0644"
  become: true
  become_user: root

- name: Put kodi sources configuration in place
  ansible.builtin.template:
    src: sources.xml.jinja2
    dest: "{{ kodi_path }}/{{ kodi_data_dir }}/sources.xml"
    owner: "{{ kodi_os_user }}"
    group: "{{ kodi_os_user }}"
    mode: "0644"
  become: true
  become_user: root

- name: Ensure background images folder
  ansible.builtin.file:
    path: "{{ kodi_path }}/background_images/"
    owner: "{{ kodi_os_user }}"
    group: "{{ kodi_os_user }}"
    mode: "0750"
    state: directory
  become: true
  become_user: root

- name: Putting background images in place
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/files/kodi_background_images/"
    dest: "{{ kodi_path }}/background_images/"
    owner: "{{ kodi_os_user }}"
    group: "{{ kodi_os_user }}"
    mode: "0644"
  become: true
  become_user: root

- name: Ensure scripts folder
  ansible.builtin.file:
    path: "{{ kodi_path }}/scripts/"
    owner: "{{ kodi_os_user }}"
    group: "{{ kodi_os_user }}"
    mode: "0750"
    state: directory
  become: true
  become_user: root

- name: Install background changer script
  ansible.builtin.template:
    src: kodi_bg_changer.sh.jinja2
    dest: "{{ kodi_path }}/scripts/kodi_bg_changer.sh"
    owner: "{{ kodi_os_user }}"
    group: "{{ kodi_os_user }}"
    mode: "0750"
  become: true
  become_user: root

- name: Remove legacy cron link
  ansible.builtin.file:
    path: /etc/cron.hourly/xbmc_bg_changer
    state: absent
  when: ansible_distribution != "LibreELEC"
  become: true
  become_user: root

- name: Remove legacy cron script
  ansible.builtin.file:
    path: "{{ kodi_path }}/scripts/xbmc_bg_changer.sh"
    state: absent
  when: ansible_distribution != "LibreELEC"
  become: true
  become_user: root

- name: Deploy systemctl background changer systemd unit
  ansible.builtin.template:
    src: kodi_bg_changer.service.jinja2
    dest: "{{ kodi_systemd_location }}/kodi_bg_changer.service"
    owner: root
    group: root
    mode: "0644"
  become: true
  become_user: root

- name: Deploy systemctl background changer systemd unit timer
  ansible.builtin.template:
    src: kodi_bg_changer.timer.jinja2
    dest: "{{ kodi_systemd_location }}/kodi_bg_changer.timer"
    owner: root
    group: root
    mode: "0644"
  become: true
  become_user: root

# /storage/.config/system.d
